# Generated by Django 3.2.11 on 2022-02-04 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roomManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeId', models.IntegerField()),
                ('rooms', models.ManyToManyField(to='roomManagement.Room')),
            ],
        ),
        migrations.CreateModel(
            name='HomeAutomationSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeAutomationSystemeManagement.home')),
            ],
        ),
    ]
