# Generated by Django 3.2.11 on 2022-02-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNumber', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('roomType', models.CharField(max_length=50)),
                ('temperature', models.IntegerField()),
                ('presence', models.BooleanField()),
                ('luminosity', models.IntegerField()),
            ],
        ),
    ]
